Add post-install script to SDK bundle

diff --git a/swift-ci/sdks/android/build b/swift-ci/sdks/android/build
--- a/swift-ci/sdks/android/build
+++ b/swift-ci/sdks/android/build
@@ -26,10 +26,13 @@ elif [ "${BUILD_VERSION}" = 'devel' ]; then
     LATEST_TOOLCHAIN_VERSION=$(curl -sL https://github.com/apple/swift/tags | grep -m1 swift-6.2-DEV | cut -d- -f8-10)
     SWIFT_TAG="swift-6.2-DEVELOPMENT-SNAPSHOT-${LATEST_TOOLCHAIN_VERSION}-a"
     SWIFT_BRANCH="swift-$(echo $SWIFT_TAG | cut -d- -f2)-branch"
-else
+elif [ "${BUILD_VERSION}" = 'trunk' ]; then
     LATEST_TOOLCHAIN_VERSION=$(curl -sL https://github.com/apple/swift/tags | grep -m1 swift-DEV | cut -d- -f7-9)
     SWIFT_TAG="swift-DEVELOPMENT-SNAPSHOT-${LATEST_TOOLCHAIN_VERSION}-a"
     SWIFT_BRANCH="development"
+else
+    echo "$0: invalid BUILD_VERSION=${BUILD_VERSION}"
+    exit 1
 fi
 
 SWIFT_BASE=$SWIFT_TAG-$HOST_OS
